---

- name: create /etc/apt/apt.conf.d/apt.conf
  copy:
    dest: /etc/apt/apt.conf.d/apt.conf
    content: ""
    force: no
    group: root
    owner: root
    mode: 644

- name: apt repository settings
  lineinfile:
    path: /etc/apt/apt.conf.d/apt.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
      - regexp: "^Acquire::ftp::proxy"
        line: 'Acquire::ftp::proxy "{{ http_proxy }}";'

      - regexp: "^Acquire::http::proxy"
        line: 'Acquire::http::proxy "{{ http_proxy }}";'
      - regexp: "^Acquire::https::proxy"
        line: 'Acquire::https::proxy "{{ https_proxy }}";'

      - regexp: "^Acquire::http::No-Cache"
        line: "Acquire::http::No-Cache true;"

      - regexp: "^Acquire::http::Pipeline-Depth"
        line: 'Acquire::http::Pipeline-Depth 0;'
  when: http_proxy and https_proxy

- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"
  when: packages

- name: download direnv
  get_url:
    url: https://github.com/direnv/direnv/releases/download/v2.13.1/direnv.linux-amd64
    dest: "/usr/local/bin/direnv"
    mode: 0755

